In [1]:
import tensorflow as tf

In [2]:
x_data = [[1,2,1],[1,3,2],
          [1,3,4],[1,5,5],
          [1,7,5],[1,2,5],
          [1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],
          [0,0,1],[0,1,0],
          [0,1,0],[0,1,0],
          [1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]] 

In [3]:
X = tf.placeholder(tf.float32, [None,3])
Y = tf.placeholder(tf.float32, [None,3])

W = tf.Variable(tf.random_normal([3,3]),name='weight')
b = tf.Variable(tf.random_normal([3]),name='bias')

In [4]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [5]:
prediction = tf.argmax(hypothesis,1)
is_correct = tf.equal(prediction,tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [6]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val,_ = sess.run([cost,W,optimizer], {X:x_data,Y:y_data})
        print step, cost_val, W_val
        
    print "Prediction : ", sess.run(prediction,{X:x_test})
    print "Accuracy : ", sess.run(accuracy,{X:x_test,Y:y_test})

0 1.89046 [[-0.13163345  0.2748313  -0.49821919]
 [ 0.31847718 -0.87361449 -0.94909942]
 [-0.83088875  0.21056914 -1.14630318]]
1 1.58457 [[-0.13610765  0.24412408 -0.46303776]
 [ 0.32689592 -0.97684693 -0.85428566]
 [-0.79573292  0.09094238 -1.06183219]]
2 1.316 [[-0.16099581  0.23561741 -0.42964292]
 [ 0.22171645 -0.96207029 -0.76388282]
 [-0.86939371  0.08329874 -0.9805277 ]]
3 1.10376 [[-0.16987649  0.21369185 -0.39883667]
 [ 0.20070048 -1.02422285 -0.68071431]
 [-0.86341184  0.00148403 -0.90469486]]
4 0.969755 [[-0.18705304  0.20479839 -0.37276664]
 [ 0.12984419 -1.02141464 -0.61266619]
 [-0.90653479 -0.01758019 -0.84250766]]
5 0.923647 [[-0.19390184  0.19212611 -0.35324559]
 [ 0.11380076 -1.0469321  -0.5711053 ]
 [-0.89890665 -0.06303547 -0.80468047]]
6 0.913291 [[-0.20215766  0.18800496 -0.34086859]
 [ 0.08801195 -1.03168452 -0.5605641 ]
 [-0.90211493 -0.0670886  -0.79741901]]
7 0.905926 [[-0.2065037   0.18226741 -0.33078501]
 [ 0.08431254 -1.02711976 -0.56142944]
 [-0.88506162 