In [1]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

print t.ndim
print t.shape
print t[0], t[1], t[-1]
print t[2:5], t[4:-1] 
print t[:2], t[3:] 

1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

print t.ndim
print t.shape

2
(4, 3)


In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4], dtype=int32)

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [7]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [8]:
(matrix1*matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

In [9]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

In [11]:
tf.random_normal([3]).eval()

array([-0.77588314,  1.23913085, -1.41319501], dtype=float32)

In [12]:
tf.random_uniform([2]).eval()

array([ 0.39413822,  0.94936323], dtype=float32)

In [13]:
tf.random_uniform([2, 3]).eval()

array([[ 0.53947985,  0.09527087,  0.90261149],
       [ 0.30484617,  0.68232226,  0.55868721]], dtype=float32)

In [14]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [15]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval()

2.5

In [16]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [17]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [18]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [19]:
tf.reduce_sum(x).eval()

10.0

In [20]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [21]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [22]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [23]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [24]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [25]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

In [26]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [27]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [29]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [30]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [31]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [32]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [33]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [34]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [35]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [36]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [37]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [38]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [39]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

(1, 4)
(2, 5)
(3, 6)


In [40]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)
