In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

In [2]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print x_data.shape, x_data, len(x_data)
print 
print y_data.shape, y_data

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25

(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [3]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [4]:
hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(1e-5)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],{X:x_data, Y:y_data})
    if step % 100 == 0:
        print step, "cost: ",cost_val, "\nPrediction: ",hy_val

0 cost:  21027.0 
Prediction:  [[ 22.04806328]
 [ 21.61978531]
 [ 24.09669304]
 [ 22.29301643]
 [ 18.63389778]
 [  7.26697063]
 [ 12.33103371]
 [  3.15051055]
 [ 14.34794331]
 [  4.25342655]
 [ 14.4857111 ]
 [ 10.6780653 ]
 [ 28.80464172]
 [ 29.29879951]
 [ 11.23783493]
 [ 18.64653969]
 [ 31.18945885]
 [ 13.34465408]
 [ 28.84173965]
 [ 25.66281319]
 [ 15.08475208]
 [ 16.79836655]
 [ 15.92454815]
 [ 31.36111832]
 [ 24.98636627]]
100 cost:  88.7105 
Prediction:  [[ 157.79551697]
 [ 185.16717529]
 [ 185.02406311]
 [ 197.75953674]
 [ 143.2940979 ]
 [  99.53504181]
 [ 143.86804199]
 [ 100.92393494]
 [ 167.53518677]
 [ 146.62892151]
 [ 141.12159729]
 [ 135.79484558]
 [ 194.86230469]
 [ 167.07516479]
 [ 143.46055603]
 [ 184.76737976]
 [ 162.27656555]
 [ 171.24031067]
 [ 187.06115723]
 [ 167.22625732]
 [ 169.31619263]
 [ 170.40229797]
 [ 162.88061523]
 [ 167.75440979]
 [ 194.32647705]]
200 cost:  82.2822 
Prediction:  [[ 157.52545166]
 [ 185.21310425]
 [ 184.86228943]
 [ 197.77949524]
 [ 143.2

In [6]:
print "Your score will be ",sess.run(hypothesis, {X:[[100,70,101]]})
print "Other scores will be ",sess.run(hypothesis, {X:[[60,70,110],[90,100,80]]})

Your score will be  [[ 181.73275757]]
Other scores will be  [[ 145.86265564]
 [ 187.23130798]]
