In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-2.9784e+15,  4.5553e-41, -2.9784e+15],
        [ 4.5553e-41,  1.3563e-19,  1.3563e-19],
        [ 1.3583e-19,  1.4584e-19,  4.0274e-11],
        [ 1.3563e-19,  3.1432e-12,  1.3563e-19],
        [ 1.3563e-19,  1.3563e-19,  1.3583e-19]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.9528,  0.5837,  0.0318],
        [ 0.6417,  0.7351,  0.4082],
        [ 0.5542,  0.3111,  0.7354],
        [ 0.1247,  0.0857,  0.2731],
        [ 0.6886,  0.2378,  0.2166]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
x[1,2] = 5
x[3][0] = 3.5
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  0,  0],
        [ 3,  0,  0],
        [ 0,  0,  0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [7]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[ 0.2146,  0.1506,  0.3735],
        [ 0.2424,  0.6880,  0.2388],
        [ 0.1845,  0.0665,  0.7172],
        [ 0.5772,  0.7792,  0.8610],
        [ 0.8377,  0.9173,  0.9224]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[ 0.1273,  0.7763,  0.5369],
        [ 0.1088,  0.3327,  0.4817],
        [ 0.9326,  0.7514,  0.0552],
        [ 0.8439,  0.7291,  0.1560],
        [ 0.4886,  0.5087,  0.4229]])
tensor([[ 0.3419,  0.9268,  0.9104],
        [ 0.3512,  1.0207,  0.7205],
        [ 1.1171,  0.8179,  0.7724],
        [ 1.4211,  1.5083,  1.0169],
        [ 1.3263,  1.4260,  1.3452]])


In [11]:
print(torch.add(x,y))

tensor([[ 0.3419,  0.9268,  0.9104],
        [ 0.3512,  1.0207,  0.7205],
        [ 1.1171,  0.8179,  0.7724],
        [ 1.4211,  1.5083,  1.0169],
        [ 1.3263,  1.4260,  1.3452]])


In [12]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3419,  0.9268,  0.9104],
        [ 0.3512,  1.0207,  0.7205],
        [ 1.1171,  0.8179,  0.7724],
        [ 1.4211,  1.5083,  1.0169],
        [ 1.3263,  1.4260,  1.3452]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.3419,  0.9268,  0.9104],
        [ 0.3512,  1.0207,  0.7205],
        [ 1.1171,  0.8179,  0.7724],
        [ 1.4211,  1.5083,  1.0169],
        [ 1.3263,  1.4260,  1.3452]])


In [14]:
print(x[:,1])

tensor([ 0.1506,  0.6880,  0.0665,  0.7792,  0.9173])


In [18]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8)
print(z)
print(x.size(),y.size(),z.size())

tensor([[-0.3853,  0.7229, -1.8552, -0.4496],
        [-0.3906, -0.8369, -0.5368, -0.4027],
        [-0.1116, -1.6416, -2.3313,  1.2063],
        [-1.7300,  1.1028, -0.7251, -0.0911]])
tensor([-0.3853,  0.7229, -1.8552, -0.4496, -0.3906, -0.8369, -0.5368,
        -0.4027, -0.1116, -1.6416, -2.3313,  1.2063, -1.7300,  1.1028,
        -0.7251, -0.0911])
tensor([[-0.3853,  0.7229, -1.8552, -0.4496, -0.3906, -0.8369, -0.5368,
         -0.4027],
        [-0.1116, -1.6416, -2.3313,  1.2063, -1.7300,  1.1028, -0.7251,
         -0.0911]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.5905])
0.5905318260192871


In [20]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([ 1.5905], device='cuda:0')
tensor([ 1.5905], dtype=torch.float64)
