In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [3]:
y = x+2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [4]:
print(y.grad_fn)

In [5]:
z = y*y*3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [6]:
print(z.grad_fn)

In [7]:
a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a)
print(a.requires_grad)

tensor([[  0.2755, -20.8036],
        [  1.8667,   1.6435]])
False


In [8]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [9]:
b = (a*a).sum()
print(b.grad_fn)

In [10]:
out.backward()

In [11]:
print(y.grad)
print(x.grad)

None
tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [15]:
x = torch.rand(3, requires_grad=True)
print(x)

y = x*2
while y.data.norm() <1000:
    print(y, y.data.norm())
    y = y*2
    
print(y)

tensor([ 0.8051,  0.7706,  0.4725])
tensor([ 1.6103,  1.5411,  0.9450]) tensor(2.4210)
tensor([ 3.2206,  3.0823,  1.8900]) tensor(4.8420)
tensor([ 6.4412,  6.1646,  3.7800]) tensor(9.6839)
tensor([ 12.8823,  12.3292,   7.5599]) tensor(19.3679)
tensor([ 25.7646,  24.6583,  15.1199]) tensor(38.7358)
tensor([ 51.5293,  49.3166,  30.2397]) tensor(77.4715)
tensor([ 103.0585,   98.6333,   60.4794]) tensor(154.9430)
tensor([ 206.1171,  197.2665,  120.9589]) tensor(309.8861)
tensor([ 412.2342,  394.5331,  241.9177]) tensor(619.7722)
tensor([ 824.4683,  789.0662,  483.8354])


In [16]:
gradients = torch.tensor([1, 2.0, 1], dtype= torch.float)
y.backward(gradients)

print(x.grad)

tensor([ 1024.,  2048.,  1024.])


In [23]:
x = torch.tensor([3], requires_grad=True)

print(x.requires_grad)
out = (x**2)

out.backward(2)
print(x.grad)

True
False


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [21]:
with torch.no_grad():
    print((x**2).requires_grad)

False
