In [1]:
import torch
import torch.nn as nn

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
cell = nn.RNN(input_size=4, hidden_size=2, batch_first= True)

inputs = torch.Tensor([h,e,l,l,o])
hidden = torch.randn(1,1,2)

for one in inputs:
    one = one.view(1,1,-1)
    out, hidden = cell(one, hidden)
    print(out, hidden)
    print("one input size", one.size(), "out size", out.size())

tensor([[[-0.6523, -0.7286]]]) tensor([[[-0.6523, -0.7286]]])
one input size torch.Size([1, 1, 4]) out size torch.Size([1, 1, 2])
tensor([[[ 0.2867,  0.6830]]]) tensor([[[ 0.2867,  0.6830]]])
one input size torch.Size([1, 1, 4]) out size torch.Size([1, 1, 2])
tensor([[[ 0.1920, -0.0193]]]) tensor([[[ 0.1920, -0.0193]]])
one input size torch.Size([1, 1, 4]) out size torch.Size([1, 1, 2])
tensor([[[ 0.2510,  0.2477]]]) tensor([[[ 0.2510,  0.2477]]])
one input size torch.Size([1, 1, 4]) out size torch.Size([1, 1, 2])
tensor([[[-0.1603, -0.2300]]]) tensor([[[-0.1603, -0.2300]]])
one input size torch.Size([1, 1, 4]) out size torch.Size([1, 1, 2])


In [5]:
inputs = inputs.view(1,5,-1)
print(inputs)
out, hidden = cell(inputs, hidden)
print("sequence input size",inputs.size(), "out size",out.size())

tensor([[[ 1.,  0.,  0.,  0.],
         [ 0.,  1.,  0.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  0.,  1.]]])
sequence input size torch.Size([1, 5, 4]) out size torch.Size([1, 5, 2])


In [6]:
hidden = torch.randn(1,3,2)

inputs = torch.Tensor([[h,e,l,l,o],[e,o,l,l,l],[l,l,e,e,l]])

In [7]:
out, hidden = cell(inputs, hidden)
print("batch input size", inputs.size(), "out size", out.size())

batch input size torch.Size([3, 5, 4]) out size torch.Size([3, 5, 2])


In [8]:
cell = nn.RNN(input_size=4, hidden_size=2)

In [9]:
inputs = inputs.transpose(dim0=0, dim1=1)

out, hidden = cell(inputs, hidden)
print("batch input size", inputs.size(), "out size", out.size())

batch input size torch.Size([5, 3, 4]) out size torch.Size([5, 3, 2])
