In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim

from torch.autograd import Variable

import numpy as np

In [7]:
xy = np.loadtxt('../data/diabetes.csv',delimiter=',', dtype=np.float32)
x_data = Variable(torch.from_numpy(xy[:, 0:-1]))
y_data = Variable(torch.from_numpy(xy[:, [-1]]))
xy[0]

array([-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
        0.00149028, -0.53117   , -0.0333333 ,  0.        ], dtype=float32)

In [3]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.L1 = nn.Linear(8,6)
        self.L2 = nn.Linear(6,4)
        self.L3 = nn.Linear(4,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        out1 = self.sigmoid(self.L1(x))
        out2 = self.sigmoid(self.L2(out1))
        y_pred = self.sigmoid(self.L3(out2))
        return y_pred
    
model = Model()

In [4]:
criterion = nn.BCELoss(size_average=True)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [5]:
for epoch in range(100):
    y_pred = model(x_data)
    
    loss = criterion(y_pred, y_data)
    if epoch%10 == 0:
        print(epoch, loss.data[0])
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 tensor(0.6819)
10 tensor(0.6780)
20 tensor(0.6745)
30 tensor(0.6714)
40 tensor(0.6687)
50 tensor(0.6662)
60 tensor(0.6641)
70 tensor(0.6621)
80 tensor(0.6604)
90 tensor(0.6589)


/home/hsue/.local/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  


In [6]:
print(x_data[0])
x_test = x_data[0]
print("predict ", model(x_test).data[0][0] >0.5)
print(y_data[0])

tensor([-0.2941,  0.4874,  0.1803, -0.2929,  0.0000,  0.0015, -0.5312,
        -0.0333])
predict  tensor(1, dtype=torch.uint8)
tensor([ 0.])


/home/hsue/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  This is separate from the ipykernel package so we can avoid doing imports until
