In [1]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)
print xy

x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [3]:
X = tf.placeholder(tf.float32, [None,4])
Y = tf.placeholder(tf.float32, [None,1])

W = tf.Variable(tf.random_normal([4,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [4]:
hypothesis = tf.matmul(X,W)+b

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
        cost_val, hy_val,_ = sess.run([cost,hypothesis,optimizer], {X:x_data,Y:y_data})
        print step, cost_val, hy_val

0 0.199319 [[ 0.47469682]
 [ 0.89157224]
 [ 0.82984805]
 [ 0.68847537]
 [ 0.79993689]
 [ 0.76098067]
 [ 0.87406397]
 [ 0.73434871]]
1 0.199316 [[ 0.474691  ]
 [ 0.89156437]
 [ 0.82984126]
 [ 0.68846977]
 [ 0.79993075]
 [ 0.76097453]
 [ 0.87405837]
 [ 0.73434252]]
2 0.199313 [[ 0.47468519]
 [ 0.89155656]
 [ 0.82983446]
 [ 0.68846416]
 [ 0.79992461]
 [ 0.76096845]
 [ 0.8740527 ]
 [ 0.73433632]]
3 0.19931 [[ 0.47467938]
 [ 0.89154869]
 [ 0.82982767]
 [ 0.68845856]
 [ 0.79991847]
 [ 0.76096231]
 [ 0.8740471 ]
 [ 0.73433012]]
4 0.199307 [[ 0.47467357]
 [ 0.89154083]
 [ 0.82982087]
 [ 0.68845296]
 [ 0.79991227]
 [ 0.76095623]
 [ 0.87404144]
 [ 0.73432386]]
5 0.199304 [[ 0.47466776]
 [ 0.89153296]
 [ 0.82981408]
 [ 0.68844736]
 [ 0.79990613]
 [ 0.76095009]
 [ 0.87403584]
 [ 0.73431766]]
6 0.199301 [[ 0.47466195]
 [ 0.89152515]
 [ 0.82980728]
 [ 0.68844175]
 [ 0.7999    ]
 [ 0.76094401]
 [ 0.87403023]
 [ 0.73431146]]
7 0.199298 [[ 0.47465613]
 [ 0.89151728]
 [ 0.82980055]
 [ 0.68843621]
 [ 0.7